### PR TITLE
improve useSubtitlesAssets

### PR DESCRIPTION
**Pull request by kdembler**

### CODE REVIEW

**Review by rafalpawlow — COMMENTED** [review]
@kdembler I agree, it looks much cleaner. But I don't like the fact that we serve `availableTracks` with empty `src`, before assets are resolved. Correct me if I'm wrong but if for some reason we will not able to resolve asset, it will be still visible in  `availableTracks` array. WDYT?

**Comment by kdembler** [comment]
Sure, I wanted to avoid a situation in which the subtitles appear in the list, but the asset resolution should be nearly instant unless something went really bad, so sure, let's filter those out. Can you do that?

**Comment by rafalpawlow** [comment]
@kdembler done, take a look

**Comment by kdembler** [comment]
Looks good. After merging you will likely need to update slightly since for example `immediatePendingAssets` doesn't exist anymore

**Pull request merged**
